apiVersion: v1
kind: Service
metadata:
  name: camic-dev
  labels:
    service: back
spec:
  type: NodePort
  selector:
    service: back
  ports:
    - name: "4010"
      port: 4010
      targetPort: 4010
      nodePort: 30401
  type: LoadBalancer
