apiVersion: apps/v1
kind: Deployment
metadata:
  name: camic-dev
  labels:
    service: back
spec:
  selector:
    matchLabels:
      service: back
  template:
    metadata:
      labels:
        service: back
    spec:
      volumes:
        - name: images
          emptyDir: {}
      containers:
        - name: mongo
          image: mongo:4.2-bionic
          ports:
            - containerPort: 27017
        - name: back
          image: ghcr.io/camicroscope/caracal:ch-container-action
          ports:
            - containerPort: 4010
          env:
            - name: JWK_URL
              value: "https://www.googleapis.com/oauth2/v3/certs"
            - name: IIP_PATH
              value: "http://localhost:8080/fcgi-bin/iipsrv.fcgi"
            - name: MONGO_URI
              value: "mongodb://localhost"
            - name: DISABLE_SEC
              value: "true"
            - name: ALLOW_PUBLIC
              value: "true"
        - name: iip
          image: camicroscope/iipimage:latest
          ports:
            - containerPort: 8080
          volumeMounts:
          - name: images
            mountPath: /images/
        - name: loader
          image: ghcr.io/camicroscope/slideloader:auto-build
          ports:
            - containerPort: 4000
          volumeMounts:
          - name: images
            mountPath: /images/
